### ISSUE TITLE
Setting combine property to false has no effect

### ISSUE THREAD

**Issue by acaprari** [caridy/yui3-gallery#1]
Setting the YAHOO_config combine property to false has no effect on the module.

This issue should be caused by the line 77, which always evaluates to true:
    l.combine = l.combine || true; /\* using the Combo Handle by default */

Changing this line with this ones will solve it:
    if (typeof l.combine == "undefined")
        l.combine = true; /\* using the Combo Handle by default */

**Comment by caridy** [comment]
Hey Alefend, thanks for the report. 

I just fixed it, and also introduce few more enhancements. Here is the commit:

http://github.com/caridy/yui3-gallery/commit/46661b98ca8f1b5e27b7667847e270e500539602

I will request the push to CDN today, in few days it should be ready :-)

Best Regards,
Caridy
