### ISSUE TITLE
bootstrap engine fails to load from yuigallery

### ISSUE THREAD

**Issue by triptych** [caridy/yui3-gallery#11]
See this error trying to load the bootstrap engine:
GET http://yui.yahooapis.com/combo?gallery-2010.12.16-18-24/build/gallery-bootstrap-engine/gallery-bootstrap-engine-min.js 400 (Bad Request)

Tried using this fiddle:

http://jsfiddle.net/triptych/Q3kFs/

**Comment by caridy** [comment]
This is because bootstrap engine is not in CDN yet. If you check the page of the module:

http://yuilibrary.com/gallery/show/bootstrap-engine

you will not see the "on cdn" label after the name of the module. It will be pushed on the next build.
