### ISSUE TITLE
YUI3 Gallery Dispatcher throwing error with malformed HTML with style tags inside

### ISSUE THREAD

**Issue by eduardolundgren** [caridy/yui3-gallery#2]
new A.Dispatcher ({
       node: '#temp',
       content: '<p>Please wait... (Injecting Static Markup)</p>'
}).set('content', "<p>HTML Fragment with style link andor script tags<style>body{color:red;}</style>asds");

Throws:

dispatcher: Initializeryui.js (line 2970)
dispatcher: dispatching a new contentyui.js (line 2970)
dispatcher: dispatching a new contentyui.js (line 2970)
Node was not found" code: "8
[Break on this error] ret = node[method](a, b, c, d, e); \nnode.js (line 722)

**Comment by eduardolundgren** [comment]
The GitHub remove the script tags from the example, see the example here: http://pastebin.com/m1c719b42

**Comment by ericf** [comment]
Fixed focus/keyboard nav modality issues. Closed by f93699b70dbd5f5728eb82c39896f438c61288a2
